server:
  port: 8081
spring:
  datasource:
    url: jdbc:clickhouse://localhost:8123/journal
    username: click
    password: 13112001UJL
    driver-class-name: cc.blynk.clickhouse.ClickHouseDriver

  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc:
          time_zone: Europe/Samara
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    path: /api-docs
