server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/journal
    username: '${POSTGRES_USER}'
    password: '${POSTGRES_PASSWORD}'
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc:
          time_zone: Europe/Samara
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
