server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5454/journal
    username: geller
    password: 13112001UJL
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc:
          time_zone: Europe/Samara
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  application:
    name: e-journal-back

auth:
  baseUrl: ${AUTH_URI:http://e-journal-auth}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}:${server.port}
  instance:
    preferIpAddress: true